import type { Internship, User } from "@/types";

// ─── Mock Internships ─────────────────────────────────────────────────────────

export const MOCK_INTERNSHIPS: Internship[] = [
  {
    _id: "1",
    name: "Frontend Developer Intern",
    company: "Google",
    applyLink: "#",
    datePublished: new Date(Date.now() - 86400000).toISOString(),
    deadlineDate: new Date(Date.now() + 15 * 86400000).toISOString(),
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    isRemote: false,
    stipend: { type: "paid", amount: 25000, currency: "INR", period: "monthly" },
    duration: { value: 3, unit: "months" },
    skills: ["React", "TypeScript", "CSS", "JavaScript"],
    degree: ["B.Tech", "BCA"],
    field: ["Computer Science", "IT"],
    experienceRequired: { min: 0, max: 6, unit: "months" },
    openings: 5,
    summary:
      "Join Google's frontend team to build next-generation web experiences. You'll work on real products used by millions of users worldwide.",
    responsibilities: [
      "Build and maintain React components",
      "Collaborate with designers on UI/UX",
      "Write unit and integration tests",
      "Participate in code reviews",
    ],
    perks: ["Certificate", "Letter of Recommendation", "Pre-Placement Offer"],
    tags: ["frontend", "react", "web"],
    source: "Google Careers",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "2",
    name: "Data Science Intern",
    company: "Microsoft",
    applyLink: "#",
    datePublished: new Date(Date.now() - 2 * 86400000).toISOString(),
    deadlineDate: new Date(Date.now() + 20 * 86400000).toISOString(),
    country: "India",
    state: null,
    city: null,
    isRemote: true,
    stipend: { type: "paid", amount: 30000, currency: "INR", period: "monthly" },
    duration: { value: 6, unit: "months" },
    skills: ["Python", "Machine Learning", "SQL", "TensorFlow"],
    degree: ["B.Tech", "M.Tech", "MCA"],
    field: ["Computer Science", "Data Science"],
    experienceRequired: { min: 0, max: 12, unit: "months" },
    openings: 3,
    summary:
      "Work with Microsoft's AI research team on cutting-edge machine learning projects. Gain hands-on experience with large-scale data pipelines.",
    responsibilities: [
      "Develop and train ML models",
      "Analyze large datasets",
      "Build data pipelines",
      "Present findings to stakeholders",
    ],
    perks: ["Certificate", "Flexible Hours", "Letter of Recommendation"],
    tags: ["data-science", "ml", "python"],
    source: "Microsoft Careers",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "3",
    name: "Backend Engineer Intern",
    company: "Flipkart",
    applyLink: "#",
    datePublished: new Date(Date.now() - 3 * 86400000).toISOString(),
    deadlineDate: new Date(Date.now() + 10 * 86400000).toISOString(),
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    isRemote: false,
    stipend: { type: "paid", amount: 20000, currency: "INR", period: "monthly" },
    duration: { value: 2, unit: "months" },
    skills: ["Node.js", "MongoDB", "REST APIs", "Docker"],
    degree: ["B.Tech"],
    field: ["Computer Science"],
    experienceRequired: { min: 0, max: 6, unit: "months" },
    openings: 8,
    summary:
      "Build scalable backend services for India's largest e-commerce platform. Work with microservices architecture and high-traffic systems.",
    responsibilities: [
      "Design and implement REST APIs",
      "Optimize database queries",
      "Write technical documentation",
      "Debug production issues",
    ],
    perks: ["Certificate", "Letter of Recommendation"],
    tags: ["backend", "nodejs", "ecommerce"],
    source: "Flipkart Careers",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "4",
    name: "UI/UX Design Intern",
    company: "Swiggy",
    applyLink: "#",
    datePublished: new Date(Date.now() - 4 * 86400000).toISOString(),
    deadlineDate: new Date(Date.now() + 25 * 86400000).toISOString(),
    country: "India",
    state: "Maharashtra",
    city: "Mumbai",
    isRemote: false,
    stipend: { type: "paid", amount: 15000, currency: "INR", period: "monthly" },
    duration: { value: 3, unit: "months" },
    skills: ["Figma", "Adobe XD", "Prototyping", "User Research"],
    degree: ["B.Des", "B.Tech"],
    field: ["Design", "Computer Science"],
    experienceRequired: { min: 0, max: 0, unit: "months" },
    openings: 2,
    summary:
      "Design intuitive user experiences for Swiggy's mobile and web platforms. Work closely with product managers and engineers.",
    responsibilities: [
      "Create wireframes and prototypes",
      "Conduct user research",
      "Design UI components",
      "Collaborate with dev team",
    ],
    perks: ["Certificate", "Flexible Hours", "Free Meals"],
    tags: ["design", "ux", "figma"],
    source: "Swiggy Careers",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "5",
    name: "Full Stack Developer Intern",
    company: "Razorpay",
    applyLink: "#",
    datePublished: new Date(Date.now() - 5 * 86400000).toISOString(),
    deadlineDate: new Date(Date.now() + 30 * 86400000).toISOString(),
    country: "India",
    state: null,
    city: null,
    isRemote: true,
    stipend: { type: "paid", amount: 35000, currency: "INR", period: "monthly" },
    duration: { value: 6, unit: "months" },
    skills: ["React", "Node.js", "PostgreSQL", "TypeScript"],
    degree: ["B.Tech", "MCA"],
    field: ["Computer Science", "IT"],
    experienceRequired: { min: 3, max: 12, unit: "months" },
    openings: 4,
    summary:
      "Build fintech products at scale. Work on payment infrastructure that processes millions of transactions daily.",
    responsibilities: [
      "Build full-stack features end-to-end",
      "Integrate payment APIs",
      "Write comprehensive tests",
      "Participate in sprint planning",
    ],
    perks: ["Certificate", "Letter of Recommendation", "Pre-Placement Offer", "Flexible Hours"],
    tags: ["fullstack", "fintech", "react"],
    source: "Razorpay Careers",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "6",
    name: "Android Developer Intern",
    company: "Zomato",
    applyLink: "#",
    datePublished: new Date(Date.now() - 6 * 86400000).toISOString(),
    deadlineDate: new Date(Date.now() + 12 * 86400000).toISOString(),
    country: "India",
    state: "Haryana",
    city: "Gurugram",
    isRemote: false,
    stipend: { type: "paid", amount: 18000, currency: "INR", period: "monthly" },
    duration: { value: 3, unit: "months" },
    skills: ["Kotlin", "Android SDK", "Jetpack Compose", "REST APIs"],
    degree: ["B.Tech"],
    field: ["Computer Science"],
    experienceRequired: { min: 0, max: 6, unit: "months" },
    openings: 6,
    summary:
      "Build features for Zomato's Android app used by 50M+ users. Work on performance optimization and new feature development.",
    responsibilities: [
      "Develop Android features using Kotlin",
      "Optimize app performance",
      "Write unit tests",
      "Fix bugs and crashes",
    ],
    perks: ["Certificate", "Letter of Recommendation"],
    tags: ["android", "kotlin", "mobile"],
    source: "Zomato Careers",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// ─── Mock User ────────────────────────────────────────────────────────────────

export const MOCK_USER: User = {
  _id: "mock-user-1",
  name: "Rahul Sharma",
  username: "rahulsharma",
  email: "rahul@example.com",
  profilePicture: null,
  phone: "+91 9876543210",
  city: "Bangalore",
  state: "Karnataka",
  country: "India",
  skills: ["React", "TypeScript", "Node.js", "Python"],
  education: [
    {
      _id: "edu-1",
      degree: "B.Tech",
      field: "Computer Science",
      institution: "IIT Bombay",
      startDate: "2021-08-01",
      endDate: "2025-05-31",
      grade: "8.5 CGPA",
    },
  ],
  experiences: [
    {
      _id: "exp-1",
      type: "internship",
      title: "Frontend Intern",
      company: "Startup XYZ",
      startDate: "2023-05-01",
      endDate: "2023-07-31",
      current: false,
      description: "Built React components and improved app performance by 30%.",
    },
  ],
  resume: {
    driveFileId: null,
    driveViewLink: null,
    uploadedAt: null,
    extractedSkills: [],
  },
  appliedInternships: [
    { internshipId: "1", appliedAt: new Date().toISOString(), status: "applied" },
    { internshipId: "2", appliedAt: new Date().toISOString(), status: "shortlisted" },
    { internshipId: "3", appliedAt: new Date().toISOString(), status: "rejected" },
  ],
  savedInternships: ["4", "5"],
  profileCompletionScore: 65,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const CATEGORIES = [
  { label: "Technology", icon: "💻", count: 1240 },
  { label: "Marketing", icon: "📣", count: 856 },
  { label: "Design", icon: "🎨", count: 634 },
  { label: "Finance", icon: "💰", count: 512 },
  { label: "Data Science", icon: "📊", count: 478 },
  { label: "Content Writing", icon: "✍️", count: 392 },
  { label: "HR & Management", icon: "👥", count: 287 },
  { label: "Operations", icon: "⚙️", count: 245 },
];

export const LOCATIONS = [
  "Work from Home",
  "Bangalore",
  "Delhi",
  "Hyderabad",
  "Mumbai",
  "Chennai",
  "Pune",
  "Kolkata",
  "Jaipur",
  "International",
];

export const PERKS_OPTIONS = [
  "Certificate",
  "Letter of Recommendation",
  "Flexible Hours",
  "Pre-Placement Offer",
  "Free Meals",
  "5 Days a Week",
  "Informal Dress Code",
];
